quentinlampin/ngx-openlayers

package.json

As mentioned in https://github.com/quentin-ol/angular2-openlayers/pull/9

add typings key to package.json

---

src/components/map.component.ts

This fixes an issue I experienced where the map sometimes has zero height upon page load.

fix zero height map

---

README.MD
src/components.ts
src/components/style.components.ts

can be used to add a custom icon to a point on the map
example in the README
I didn't test all the options explicitly, but there shouldn't be any problems.

Add Icon style feature

---

src/components/map.component.ts

Have the events of the Map as output available to the user

map event outputs

---

README.MD
src/components/map.component.ts

Fix resize problem

---

src/components/feature.component.ts

I got an error using the features id, since ngOnChange seemed to be fired before ngOnInit and due to this instance being undefined.

fixed undefined instance error

---

dist/components/map.component.js
src/components/map.component.ts

fixed not updating size

---

src/components/interactions/index.ts
src/components/interactions/modify.component.ts
src/index.ts

Add modify interaction (e.g. https://openlayers.org/en/latest/examples/modify-features.html?q=modify)

feat(ModifyInteractionComponent): add modify interaction to be able to modify feature(s)

---

src/components/interactions/index.ts
src/components/interactions/translate.component.ts
src/index.ts

Add translate interaction (e.g. https://openlayers.org/en/latest/examples/translate-features.html)

feat(TranslateInteractionComponent): add interaction to be able to move feature(s)

---

src/components/interactions/index.ts
src/components/interactions/select.component.ts
src/index.ts

Add select interaction (e.g. https://openlayers.org/en/latest/examples/select-features.html)

feat(SelectInteractionComponent): add new interaction to ba able to select feature(s)

---

src/components/sources/vector.component.ts

can't seem to test it myself still but I think this single line addition should be all that's needed to allow a loading strategy to be used.....

Added LoadingStrategy @Input 

---

package.json
src/components/layers/index.ts
src/components/layers/layerimage.component.ts
src/components/sources/imagewms.component.ts
src/components/sources/index.ts
src/index.ts

New features:
- ol.layer.Image
- ol.source.ImageWMS

Adding LayerImageComponent and SourceImageWMSComponent

---

src/components/sources/xyz.component.ts

@Neonox31 @davinkevin 
Update instance on change and refresh instance on url change.

feat(sources): trigger refresh on property changes for XYZ Component

---

example/.angular-cli.json
package.json
src/components/controls/zoom.component.ts
src/components/controls/zoomtoextent.component.ts

- adding options to ControlZoomComponent and ControlZoomToExtentComponent 
- implementing openlayers stylesheet to example project

Updating zoom and zoom to extent components

---

src/components/sources/osm.component.ts
src/components/sources/xyz.component.ts

@Neonox31 @davinkevin @Yakoust

Feat add tilegrid child component to source xyz component

---

src/components/layers/index.ts
src/components/layers/layer.component.ts
src/components/layers/layergroup.component.ts
src/components/layers/layerimage.component.ts
src/components/layers/layertile.component.ts
src/components/layers/layervector.component.ts
src/components/layers/layervectortile.component.ts
src/index.ts

I added the LayerGroup component.
It can be used with `<aol-layer-group></aol-layer-group>` element.
This closes issue #100

feat(layergroup): new component LayerGroupComponent

---

src/components/controls/scaleline.component.ts

feat(scaleline): add input units to scaleline component

---

src/components/layers/layer.component.ts
src/components/layers/layerimage.component.ts
src/components/layers/layertile.component.ts
src/components/layers/layervector.component.ts
src/components/layers/layervectortile.component.ts

@davinkevin @Neonox31 @aymeric-duchein

fix(layer): remove useless input and change layer component init

---

example/src/app/app.component.html
src/components/view.component.ts

Hello @quentin-ol 
I added a new input value on the view component to animate the zoom.
Unlike other inputs on the View component, this one doesn't follow OpenLayers View API, but I cannot think of a better way.
Thanks

feat(view): set animation on zoom changes

---

example/.angular-cli.json
example/package.json
example/src/app/app.component.html
example/src/app/app.component.ts
example/src/app/app.module.ts
example/src/app/app.routing.ts
example/src/app/basic/basic.component.html
example/src/app/basic/basic.component.ts
example/src/app/cluster/cluster.component.html
example/src/app/cluster/cluster.component.ts
src/components/sources/cluster.component.ts
src/components/sources/index.ts
src/index.ts

Added the cluster component and the associated demo page.
Preparing the router to add multiple demo pages for later.

[WIP] feat(cluster): add cluster componant and demo

---

src/components/sources/cluster.component.ts

Need to add geometryFunction to cluster component to avoid assertion error with native geometryFunction while getting features asynchonously .
@davinkevin @Neonox31

add geaometryFunction input to cluster component

---

src/components/interactions/modify.component.ts

Add source input to modify interaction.
@davinkevin @Neonox31

feat(modify-interaction): add source input

---

projects/ngx-openlayers/src/lib/sources/source.component.ts

Fix check host instance source

---

projects/ngx-openlayers/src/lib/view.component.ts
src/app/basic/basic.component.ts

feat(view): add zoom change output

---

projects/ngx-openlayers/src/lib/sources/imagearcgisrest.component.ts
projects/ngx-openlayers/src/public_api.ts
src/app/app.module.ts
src/app/app.routing.ts
src/app/arcgis-image/arcgis-image.component.ts
src/app/draw-polygon/draw-polygon.component.ts
src/app/example-list.ts
src/app/modify-polygon/modify-polygon.component.ts

Add Image ArcGIS MapServer.
https://openlayers.org/en/latest/examples/arcgis-image.html

feat(source): add Image ArcGIS source

---

projects/ngx-openlayers/src/lib/sources/cluster.component.ts

I need wrapX option for my project, i propose to add it.
http://openlayers.org/en/latest/apidoc/module-ol_source_Cluster.html#~Options

feat(cluster): add wrapX option

---

README.MD

Improve documentation

---

projects/ngx-openlayers/src/lib/sources/imagearcgisrest.component.ts
projects/ngx-openlayers/src/lib/sources/osm.component.ts
projects/ngx-openlayers/src/lib/sources/raster.component.ts
projects/ngx-openlayers/src/lib/sources/source.component.ts
projects/ngx-openlayers/src/lib/sources/xyz.component.ts
src/app/example-list.ts
src/app/raster/raster.component.ts

When we change/update sources of raster, it does not get updated.
I also think I have encountered an existing [issue](https://github.com/openlayers/openlayers/issues/7734) and I added a workaround as an example (blocking in my project).  I also add TileEvents in XXZ and OSM sources  in this way.

feat(raster): not updated when source change

---

projects/ngx-openlayers/src/lib/layers/layervector.component.ts

Add missing API properties for vector layer

---

projects/ngx-openlayers/src/lib/sources/imagearcgisrest.component.ts
src/app/raster/raster.component.ts

When I change params, they are not updated.
I also fix raster example.
@Neonox31 / @Yakoust

fix(source): update params ImageArcgisRest

---

projects/ngx-openlayers/src/lib/sources/utfgrid.component.ts
projects/ngx-openlayers/src/public_api.ts
src/app/app.module.ts
src/app/app.routing.ts
src/app/example-list.ts
src/app/utfgrid/utfgrid.component.ts

Related to https://github.com/quentin-ol/ngx-openlayers/pull/179 already merged on master
BTW source has been renamed since ol5

feat(source): add UTF grid source

---

src/app/app.module.ts
src/app/app.routing.ts
src/app/example-list.ts
src/app/image-static/image-static.component.ts

@kekel87 / @Neonox31 
can you please review?

doc: add image static example

---

src/app/app.module.ts
src/app/app.routing.ts
src/app/example-list.ts
src/app/select-interaction/select-interaction.component.ts

@kekel87 / @Neonox31 
can you please review?

doc: select interaction example

---

src/app/app.module.ts
src/app/app.routing.ts
src/app/example-list.ts
src/app/tile-json/tile-json.component.ts

@kekel87 / @Neonox31 
can you please review?

doc: add tile json source example

---

projects/ngx-openlayers/src/lib/sources/imagestatic.component.ts
src/app/image-static/image-static.component.ts

feat(source:imagestatic): refresh layer source when url change

---

projects/ngx-openlayers/src/lib/graticule.component.ts
src/app/app.module.ts
src/app/app.routing.ts
src/app/example-list.ts
src/app/graticule/graticule.component.ts

Handle graticule destruction.
Add graticule example.
@Neonox31 / @Yakoust

feat(graticule): unregister on destroy

---

projects/ngx-openlayers/src/lib/sources/cluster.component.ts
src/app/cluster/cluster.component.ts

Add distance cluster example.
@Neonox31 / @Yakoust

feat(cluster): update distance input

---

projects/ngx-openlayers/src/lib/sources/imagearcgisrest.component.ts
src/app/arcgis-image/arcgis-image.component.ts

Add image load events.
@Neonox31 / @Yakoust

feat(imagearcgis): add image events

---

projects/ngx-openlayers/src/lib/view.component.ts

Add missing input according to Openlayer 6.3.x:
- constrainOnlyCenter
- smoothExtentConstraint
- constrainResolution
- smoothResolutionConstraint

feat(view): add missing inputs

---

projects/ngx-openlayers/src/lib/view.component.ts

Add missing input according to Openlayer 6.3.x:
- multiWorld

feat(view): add multiWorld

---

projects/ngx-openlayers/src/lib/styles/stroke.component.ts

From `'ol/colorLike'` To `'ol/colorlike'`

fix(stroke): fix ColorLike import path

---

package.json
yarn.lock

PR to fix vulnerability issues found on next branch : https://github.com/quentin-ol/ngx-openlayers/actions/runs/8422142260/job/23060739647

chore: fix vulnerabilities

---

README.MD
projects/ngx-openlayers/src/lib/sources/vector.component.ts

feat(source-vector): support of 'loader' input

---

package.json
projects/ngx-openlayers/package.json
projects/ngx-openlayers/src/lib/controls/mouseposition.component.ts
projects/ngx-openlayers/src/lib/controls/scaleline.component.ts
projects/ngx-openlayers/src/lib/layers/layervectortile.component.ts
projects/ngx-openlayers/src/lib/sources/bingmaps.component.ts
projects/ngx-openlayers/src/lib/styles/text.component.ts
src/app/image-static/image-static.component.ts
yarn.lock

feat: update openlayers to `~7.5.2`

---

package.json
yarn.lock

build: update commit-and-tag-version to 12.5.0

---

package.json
projects/ngx-openlayers/package.json
projects/ngx-openlayers/src/lib/formats/format.component.ts
projects/ngx-openlayers/src/lib/formats/mvt.component.ts
projects/ngx-openlayers/src/lib/sources/cluster.component.ts
projects/ngx-openlayers/src/lib/sources/vectortile.component.ts
yarn.lock

BREAKING CHANGE: `ol` peer dep is now `~9.2.4`
BREAKING CHANGE: see all breaking changes from `ol` `9.0.0` (https://github.com/openlayers/openlayers/blob/main/changelog/v9.0.0.md)
Closes #300

feat: update openlayers to `9.2.4`

---

package.json
projects/ngx-openlayers/src/lib/formats/format.component.ts
projects/ngx-openlayers/src/lib/formats/mvt.component.ts
projects/ngx-openlayers/src/lib/map.component.ts
projects/ngx-openlayers/src/lib/sources/vectortile.component.ts
yarn.lock

BREAKING CHANGE: `ol` peer dep is now `~10.5.0`
BREAKING CHANGE: see all breaking changes from `ol` `10.0.0` (https://github.com/openlayers/openlayers/blob/main/changelog/v10.0.0.md)

feat: update openlayers to `10.5.0`

---

CONTRIBUTING.md

docs: add contributing file

---

projects/ngx-openlayers/src/lib/layers/layer.component.ts
projects/ngx-openlayers/src/lib/layers/layergroup.component.ts
projects/ngx-openlayers/src/lib/layers/layerimage.component.ts
projects/ngx-openlayers/src/lib/layers/layertile.component.ts
projects/ngx-openlayers/src/lib/layers/layervector.component.ts
projects/ngx-openlayers/src/lib/layers/layervectortile.component.ts

fix(layers): add missing inputs

---

README.MD

Add dependencies for Angular and Openlayer  in README
