quentinlampin/ngx-openlayers

.gitignore, .npmignore, package.json, src/components.ts, src/components/controls/controls.ts, src/components/layer.components.ts, src/components/map.component.ts, src/components/source.components.ts, src/components/view.component.ts, src/index.ts, tsconfig.json
Making this library aot friendly using [this guide](https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.h3wqe3ai9)
I started this work as I think it has to be done sooner or later (rater sooner then later) and I think it might also solve the issue #19, since both throw the same exception.
I replaced the tsc compiler with the ngc compiler, did the needed changes in tsconfig.json, .gitignore and .npmignore and was able to compile resulting in all the metadata and factory files being generated, but when trying to build a small example using aot I still get the error: ```Unexpected value 'AngularOpenlayersModule' imported by the module 'AppModule'```. Currently I'm out of ideas, but I'll defenitly continue the research and try to finish it.
In the mean …
=> Aot support

package.json
An error occurred when you try to build the application due to wrong version of typings for OpenLayers. Some methods used in the StyleComponent object were not defined. The ngc build returned the following errors : 
```
Error at /Users/kdavin/Workspace/Airbus/webfactory/angular-openlayers/src/components/style.components.ts:60:21: Property 'setRadius' does not exist on type 'Circle'.
Error at /Users/kdavin/Workspace/Airbus/webfactory/angular-openlayers/src/components/style.components.ts:67:24: Property 'setImage' does not exist on type 'Style'.
Error at /Users/kdavin/Workspace/Airbus/webfactory/angular-openlayers/src/components/style.components.ts:73:43: Property 'setRadius' does not exist on type 'Circle'.
Error at /Users/kdavin/Workspace/Airbus/webfactory/angular-openlayers/src/components …
```
=> fix(types): upgrade types of OpenLayers

example/package.json
To allow the example to be launch, a missing dependency is added to `package.json`
=> fix(example): add form to package.json

dist/components/map.component.js, src/components/map.component.ts
PR #53 raises three issues that I haven't seen at first.
1. AfterViewChecked is not imported. (ngc didn't catch it at first!)
2. the ngAfterViewChecked callback is called too frequently causing high CPU usages.
3. when using a md-sidenav layout (material-design) where the map is the sole main content that extends to the bottom of the page, the updateSize method is called repeatedly and and the map scrolls upwards endlessly.
=> Revert "fixed not updating size"

src/components/sources/geojson.component.ts, src/components/sources/index.ts, src/index.ts
I need to use some GeoJSON format vector layers and started out with the solution from #41 (using afterContentInit) but ran into chicken and egg hell trying to style the layer. Thus, this solution. I can add to the example if this pull is approved. Basic usage (From my project):
```
<aol-layer-vector *ngIf="aol_show_AZ">
<aol-source-geojson [url]="'/assets/layers/04_AZ_County_Clipped.geojson'">
<aol-style>
<aol-style-stroke [color]="'lightblue'" [width]="width"></aol-style-stroke>
</aol-style>
</aol-source-geojson>
</aol-layer-vector>
```
=> Geojson source

package.json
With a pinned dependency, we force this specific version of openlayers onto every project using our package.
I've relaxed the check to work with all versions of openlayers whose API we support.
Ideally we should probably turn the `dependency` into a `peerDependency`, then it would be the user's responsibility to require the desired version of openlayers in his/her project.
=> Relax version requirement

src/components/sources/vector.component.ts
Add `url` and `format` parameters to `aol-source-vector`. 
Openlayer doc: http://openlayers.org/en/latest/apidoc/ol.source.Vector.html
=> add url and format to source-vector component

.travis.yml, example/package.json
Add continuous integration through Travis tool (https://travis-ci.org/)
**Pipeline is composed by 3 steps :**
1. **Build library** which triggers `npm install` and `npm pack` and stores it in cache for next stage
2. **Build demo** which triggers `npm install` for example cli project and includes built library of the previous stage (via `npm uninstall` and `npm install`)
3. **Deploy library release** which deploys the packed library of the first stage in Github releases when adding tags only
4. **Deploy demo pages** which deploys the example cli project on Github pages (tags only)
**Notices :** 
- test stage is not implemented yet, maybe in a future PR
- don't forget to add the `GITHUB_OAUTH_TOKEN` env var in Travis setting for Github deployments
=> Add continuous integration

.gitignore, example/package.json, src/components/index.ts, src/components/sources/index.ts, src/components/sources/tilewmts.component.ts, src/components/tilegridwmts.component.ts, src/components/view.component.ts, src/index.ts
Grid tile wmts has to be a child component of wms source to be compliant
with Openlayers architecture. 
As the tileGrid parameter of source WMTS
is mandatory, source intance is created after content initialization
with tile grid child component instance as value for tileGrid
@davinkevin @Neonox31 @Yann29
=> feat(SourceTileWMTSComponent): add wmts source component and wmts grid tile component

package.json, src/components/interactions/translate.component.ts
Implementing hitTolerance option and fires (change, propertychange, translateend, translatestart, translating) into existing translate interaction, due to their useful properties.
=> Updating translate interaction

src/components/sources/xyz.component.ts
Added the [tileLoadFunction](https://openlayers.org/en/latest/apidoc/ol.source.XYZ.html#getTileLoadFunction) that wasn't accessible in the SourceXYZComponent.
This function can help when dealing with authenticated sources.
=> feat(SourceXYZComponent): add tileLoadFunction input

src/components/graticule.component.ts, src/components/index.ts, src/index.ts
I added the Graticule component.
It can be used with `<aol-graticule></aol-graticule>` element.
Waiting for DefinitelyTyped/DefinitelyTyped#21074 before it can be used.
@davinkevin
=> feat(graticule): Adding GraticuleComponent

src/components/sources/xyz.component.ts
If I try to add a source.XYZ on the map, it is not displayed.
The official example for OpenLayers XYZ cannot work ([http://openlayers.org/en/latest/examples/xyz.html](http://openlayers.org/en/latest/examples/xyz.html))
This fix solves this problem.
@aymeric-duchein
=> fix(source.XYZ): instantiate XYZ source even if no tileGrid is provided

.travis.yml, package.json
Add a NPM auto publish stage in .travis.yml file
Now, you could use this following command to release a new version : `npm run release && git push && git push --tags`
The commit and tag are automatically created and after push travis auto deploys newly created NPM package according to tag.
Don't forget to add `NPM_TOKEN` and `NPM_EMAIL` travis variables.
=> chore(ci): add auto publish stage

example/package.json, package.json
since it's only necessary for the example, I moved @angular/animations into dev dependencies to avoid warning messages when using ngx-openlayers with recent angular versions.
=> refactor(misc): fix dev dependencies

projects/ngx-openlayers/src/lib/sources/source.component.ts
The instance wasn't checked causing some `Cannot read property 'setSource' of undefined` when using *ngIf or other structural directives.
@Neonox31 @davinkevin @Yakoust @dabbid
=> Fix check host instance source

projects/ngx-openlayers/src/lib/sources/imagewms.component.ts, projects/ngx-openlayers/src/lib/sources/tilewms.component.ts
Hello,
When updating params input for TileWMS and ImageWMS, the source is not updated. This is important for time-based or elevation-based imagery layers.  
This PR fixes this.  
See corresponding API on OpenLayers:
- http://openlayers.org/en/latest/apidoc/module-ol_source_TileWMS-TileWMS.html#updateParams
- http://openlayers.org/en/latest/apidoc/module-ol_source_ImageWMS-ImageWMS.html#updateParams
=> Update params for TileWMS and ImageWMS

projects/ngx-openlayers/src/lib/sources/imagestatic.component.ts, projects/ngx-openlayers/src/lib/sources/imagewms.component.ts, src/app/app.module.ts, src/app/app.routing.ts, src/app/color-select-hover/color-select-hover.component.ts, src/app/example-list.ts, src/app/image-wms/image-wms.component.ts
I need to get the image load end event on a static image.
I added the 3 corresponding events (imageloadstart, imageloadend, imageloaderror), see here :+1: http://openlayers.org/en/latest/apidoc/module-ol_source_ImageWMS-ImageWMS.html
(The documentation only exits for ImageWMS, but it works for ImageStatic too).
=> feat(image): add image loading events

projects/ngx-openlayers/src/lib/view.component.ts, src/app/app.module.ts, src/app/app.routing.ts, src/app/example-list.ts, src/app/view-projection-update/view-projection-update.component.ts
Hello,
This change brings the fact to dynamically update the projection of the map, as it is possible in OpenLayers example here: http://openlayers.org/en/latest/examples/reprojection-by-code.html  
The change is to be applied only after #183 is merged.
I also added the example "view-projection-update" in the demo project to see it working.
=> feat(view): dynamically update projection [OL5]

projects/ngx-openlayers/src/lib/controls/overviewmap.component.ts, src/app/app.module.ts, src/app/app.routing.ts, src/app/example-list.ts, src/app/overview/overview.component.ts
Hello,
When we dynamically update the view projection, it breaks the overview display because it uses a different view in its own map.  
With this change, when we update the overview map view, we also reload the instance.
=> feat(overviewmap): refresh overview when the view changes

documentation/README.md, projects/ngx-openlayers/src/lib/map.component.ts, src/app/map-position/map-position.component.ts
This PR is only for wrapping the map events movestart from openlayers. I added an example of the use in the 'Map Position' example.
=> Adding MapEvents onMoveStart

projects/ngx-openlayers/src/lib/styles/stroke.component.ts
Openlayers accept ColorLike as Color input: https://openlayers.org/en/latest/apidoc/module-ol_style_Stroke-Stroke.html
=> feat(stroke): add ColorLike typing to color input

package.json, projects/ngx-openlayers/package.json, projects/ngx-openlayers/src/lib/sources/imagestatic.component.ts, projects/ngx-openlayers/src/lib/styles/icon.component.ts, src/app/overlay/overlay.component.ts, yarn.lock
BREAKING CHANGE: `ol` peer dep is now `8.2.0`
BREAKING CHANGE: see all breaking changes from `ol` `8.0.0` (https://github.com/openlayers/openlayers/blob/main/changelog/upgrade-notes.md#800)
=> feat: update openlayers to `8.2.0`
